[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = false

[profile.dev]
opt-level = "s"
lto = "thin"
debug = 1

[workspace.dependencies]
mlua = { version = "0.9.1", features = ["lua51", "module", "serialize"] }
serde = "1"
serde_json = "1"
serde_derive = "1"
netidx = "0.25"
netidx-core = "0.25"
netidx-derive = "0.22"
compact_str = { version = "0.7", features = ["serde"] }
bytes = "1"
fxhash = "0.2"
enumflags2 = "0.7.8"
once_cell = "1"
parking_lot = "0.12"
nalgebra = { version = "0.32", features = ["serde-serialize"] }
immutable-chunkmap = { version = "2.0.2", features = ["serde"] }
anyhow = "1"
paste = "1"

[workspace]
resolver = "2"
members = [
	"dcso3",
	"bflib",
	"bfdb",
]
