[package]
name = "bflib"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
debug = false
lto = true

[lib]
name = "bflib"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.9.1", features = ["lua51", "module", "serialize"] }
serde = "1"
serde_json = "1"
serde_derive = "1"
netidx = "0.25"
netidx-core = "0.25"
netidx-derive = "0.22"
compact_str = "0.7"
bytes = "1"
fxhash = "0.2"