[package]
name = "bfdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bflib = { version = "0.1.0", path = "../bflib" }
mlua = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_derive = { workspace = true }
compact_str = { workspace = true }
bytes = { workspace = true }
fxhash = { workspace = true }
enumflags2 = { workspace = true }
