name: Build BFNext

on: 
  workflow_dispatch: 
    inputs:
      branch:
        type: string
        default: master
      

env:
  CARGO_TERM_COLOR: always
  LUA_LIB: $GITHUB_WORKSPACE
  LUA_LINK: "dylib"
  LUA_LIB_NAME: "lua"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release --package=bflib
      
    - name: Show Build Folder
      run: ls -l $GITHUB_WORKSPACE/target/release/
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: BuddybotBuild
        path: $GITHUB_WORKSPACE/target/release/bflib.dll
